[env:esp32-s2-saola-1]
platform = espressif32 @ 6.13.0
board = esp32-s2-saola-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/build_web.py
