<script lang="ts">
	import PlannedApiCard from '$lib/components/PlannedApiCard.svelte';
	import { plannedApi } from '$lib/contracts/plannedApi';
</script>

<div class="w-full max-w-none 2xl:max-w-7xl mx-auto p-4 max-[320px]:px-2">
	<h2 class="text-2xl font-bold">Alarm History</h2>
	<p class="mt-2 opacity-80 leading-relaxed">
		Planned: view alarm events generated by the ESP32 runtime.
	</p>
	<ul class="list-disc ml-5 mt-3 text-sm opacity-80 leading-relaxed">
		<li>
			<b>Event list</b>: timestamp, alarm name, severity, state (triggered/cleared), message.
		</li>
		<li>
			<b>Delivery status</b>: whether a Telegram message was sent successfully (and retry outcome).
		</li>
		<li>
			<b>Retention</b>: fixed-size ring buffer (bounded history) and rollover behavior.
		</li>
		<li>
			<b>Export</b>: optional download/export for diagnostics.
		</li>
	</ul>

	<div class="mt-6">
		<PlannedApiCard section={plannedApi.alarms} />
	</div>
</div>
