[platformio]
default_envs = esp32dev_dbg
extra_configs = 
	factory_settings.ini
	features.ini
	secrets.ini

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev_rel]
build_type = release
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder, default
upload_speed = 2000000
monitor_speed = 115200
build_flags =
   ${factory_settings.build_flags}
   ${features.build_flags}
   -Os
   -DRELEASE
   -DCA_USE_LITTLEFS
   -DLOGGER_LOG_LEVEL=2
   -DCORE_DEBUG_LEVEL=0
   -D BUILD_TARGET=\"$PIOENV\"
   -D APP_NAME=\"PlantStatus\"
   -D APP_VERSION=\"2.0.0\"
   -D ESP32SVELTEKIT_RUNNING_CORE=0
   -D EMBED_WWW
   -D SERIAL_INFO
board_build.partitions = partitions/esp32_partition_no_ota.csv
;board_build.partitions = partitions/esp32_partition_app1332k_fs1434k.csv
;board_build.partitions = partitions/esp32_partition_app1572k_fs983k.csv
board_build.filesystem = littlefs
#board_build.f_cpu = 160
extra_scripts = 
   pre:scripts/build_interface.py
lib_deps =
   ArduinoJson@>=7.0.0
   claws/BH1750
   adafruit/DHT sensor library
   adafruit/RTClib@^2.1.1
   SPI

[env:esp32dev_test]
extends = env:esp32dev_rel
build_type = debug
build_flags =
   ${factory_settings.build_flags}
   ${features.build_flags}
   -Os
   -DCA_USE_LITTLEFS
   -DVERBOSE_MODE
   -DLOGGER_LOG_LEVEL=3
   -D BUILD_TARGET=\"$PIOENV\"
   -D APP_NAME=\"PlantStatus\"
   -D APP_VERSION=\"2.0.0\"
   -D ESP32SVELTEKIT_RUNNING_CORE=0
   -D EMBED_WWW
   -D SERIAL_INFO
   -DCORE_DEBUG_LEVEL=3

[env:esp32dev_dbg]
extends = env:esp32dev_rel
build_type = debug
build_flags =
   ${factory_settings.build_flags}
   ${features.build_flags}
   ${secrets.build_flags}
   -Os
   -DCA_USE_LITTLEFS
   -DTELEGRAM_TLS_VERIFY=1
   -DVERBOSE_MODE
   -DLOGGER_LOG_LEVEL=5
   -D BUILD_TARGET=\"$PIOENV\"
   -D APP_NAME=\"PlantStatus\"
   -D APP_VERSION=\"2.0.0\"
   -D ESP32SVELTEKIT_RUNNING_CORE=0
   -D EMBED_WWW
   -D SERIAL_INFO
   -DCORE_DEBUG_LEVEL=3
