[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32cam
framework = arduino

upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

board_build.partitions = huge_app.csv

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DAPP_VERSION=\"0.1.0\"
  -DAPP_TELEGRAM_INSECURE_TLS_DEFAULT=0
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src

lib_ldf_mode = chain+

lib_deps =
  Networking
