/** BlazePose 33-landmark index labels (MediaPipe Pose Landmarker). */
export const BLAZEPOSE_LANDMARK_NAMES: readonly string[] = [
  'Nos',
  'L-Oko wew.',
  'L-Oko',
  'L-Oko zew.',
  'P-Oko wew.',
  'P-Oko',
  'P-Oko zew.',
  'L-Ucho',
  'P-Ucho',
  'Usta L',
  'Usta P',
  'L-Bark',
  'P-Bark',
  'L-Łokieć',
  'P-Łokieć',
  'L-Nadgarstek',
  'P-Nadgarstek',
  'L-Mały palec',
  'P-Mały palec',
  'L-Palec wsk.',
  'P-Palec wsk.',
  'L-Kciuk',
  'P-Kciuk',
  'L-Biodro',
  'P-Biodro',
  'L-Kolano',
  'P-Kolano',
  'L-Kostka',
  'P-Kostka',
  'L-Pięta',
  'P-Pięta',
  'L-Stopa',
  'P-Stopa',
];